### ISSUE TITLE
Create an Installer for major or milestones versions

### ISSUE THREAD

**Issue by Zeniac** [dot42/dot42#28] opened 2016-02-08 19:49 UTC
Most people that I refer DOT42 to, instantly like the concept, but many have difficult compiling the package by themselves, or perceive having to compile the package by themselves as a barrier to start using the software. An installer, like the one that was available before, will great help the acceptance of the project.

**Comment by OlafPettersson** [comment] 2016-02-09 12:17
Duplicate of #26

**Comment by OlafPettersson** [comment] 2016-03-12 13:24
https://github.com/dot42/dot42/releases

**Closed by OlafPettersson** 2016-03-12 13:24 UTC
